title: GhaSShee
email: ghasshee@gmail.com
description:
  Now under construction of AVM/ethereum project, if you want to know about this project ,
  email me . I like Beech Forest . Because it is a final state of Forest State Transition .
baseurl: ""
url: "https://ghassheee.github.io"
twitter_username: ghasshee
github_username:  ghasshee

markdown: kramdown
permalink: /:title/
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

collections:
  build:
    output: true
    permalink: /build/:path/
  ethereum:
    output: true
    permalink: /ethereum/:path/
  math:
    output: true
    permalink: /math/:path/
  category:
    output: true
    permalink: /category/:path/
  functional:
    output: true
    permalink: /functional/:path/
  posix:
    output: true
    permalink: /posix/:path/
  diary:
    output: true
    permalink: /diary/:path/
  os:
    output: true
    permalink: /os/:path/
  linux:
    output: true
    permalink: /linux/:path/
  tool:
    output: true
    permalink: /tool/:path/
